spring:
  cloud:
    gateway:
      routes:
        - id: REMD_users
          uri: http://localhost:9003
          predicates:
            - Path=/user/**

        - id: REMD_notifications
          uri: http://localhost:9002
          predicates:
            - Path=/notification/**

        - id: REMD_annonces
          uri: http://localhost:9000
          predicates:
            - Path=/annonces/**

        - id: REMD_articles
          uri: http://localhost:9001
          predicates:
            - Path=/articles/**


